models/MailQueue.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "mail_queue".
 *
 * @property int $id
 * @property string|null $sender_name
 * @property string|null $sender_email
 * @property string|null $email_to
 * @property string|null $cc
 * @property string|null $bcc
 * @property string|null $subject
 * @property string|null $html_body
 * @property string|null $text_body
 * @property string|null $reply_to
 * @property string|null $charset
 * @property string $created_at
 * @property int|null $attempts
 * @property string|null $last_attempt_time
 * @property string|null $sent_time
 * @property string|null $time_to_send
 * @property string|null $swift_message
 * @property string|null $attachments
 * @property int $sent
 * @property string $email_template
 */
class MailQueue extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mail_queue';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['sender_name', 'sender_email', 'email_to', 'cc', 'bcc', 'html_body', 'text_body', 'reply_to', 'swift_message', 'attachments'], 'string'],
            [['created_at', 'last_attempt_time', 'sent_time', 'time_to_send'], 'safe'],
            [['attempts', 'sent'], 'integer'],
            [['subject', 'charset', 'email_template'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sender_name' => 'Sender Name',
            'sender_email' => 'Sender Email',
            'email_to' => 'To',
            'cc' => 'Cc',
            'bcc' => 'Bcc',
            'subject' => 'Subject',
            'html_body' => 'Body',
            'text_body' => 'Text Body',
            'reply_to' => 'Reply To',
            'charset' => 'Charset',
            'created_at' => 'Date Queued',
            'attempts' => 'Attempts',
            'last_attempt_time' => 'Last Attempt Time',
            'sent_time' => 'Sent Time',
            'time_to_send' => 'Time To Send',
            'swift_message' => 'Swift Message',
            'attachments' => 'Attachments',
            'sent' => 'Sent',
            'email_template' => 'Email Template',
        ];
    }
}

controllers/MailQueueController.php
<?php

namespace app\controllers;

use Yii;
use app\models\MailQueue;
use app\models\MailQueueSearch;
use app\controllers\MainController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MailQueueController implements the CRUD actions for MailQueue model.
 */
class MailQueueController extends MainController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MailQueue models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MailQueueSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MailQueue model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new MailQueue model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MailQueue();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing MailQueue model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing MailQueue model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MailQueue model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MailQueue the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MailQueue::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    public function actionClear(){
        MailQueue::deleteAll();
        return $this->redirect(['index']);
    }
}

views/mail-queue/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MailQueue */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mail-queue-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'sender_name')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'sender_email')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'email_to')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'cc')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'bcc')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'subject')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'html_body')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'text_body')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'reply_to')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'charset')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'attempts')->textInput() ?>

    <?= $form->field($model, 'last_attempt_time')->textInput() ?>

    <?= $form->field($model, 'sent_time')->textInput() ?>

    <?= $form->field($model, 'time_to_send')->textInput() ?>

    <?= $form->field($model, 'swift_message')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'attachments')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'sent')->textInput() ?>

    <?= $form->field($model, 'email_template')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/mail-queue/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MailQueueSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mail-queue-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'sender_name') ?>

    <?= $form->field($model, 'sender_email') ?>

    <?= $form->field($model, 'email_to') ?>

    <?= $form->field($model, 'cc') ?>

    <?php // echo $form->field($model, 'bcc') ?>

    <?php // echo $form->field($model, 'subject') ?>

    <?php // echo $form->field($model, 'html_body') ?>

    <?php // echo $form->field($model, 'text_body') ?>

    <?php // echo $form->field($model, 'reply_to') ?>

    <?php // echo $form->field($model, 'charset') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'attempts') ?>

    <?php // echo $form->field($model, 'last_attempt_time') ?>

    <?php // echo $form->field($model, 'sent_time') ?>

    <?php // echo $form->field($model, 'time_to_send') ?>

    <?php // echo $form->field($model, 'swift_message') ?>

    <?php // echo $form->field($model, 'attachments') ?>

    <?php // echo $form->field($model, 'sent') ?>

    <?php // echo $form->field($model, 'email_template') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/mail-queue/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MailQueue */

$this->title = 'Create Mail Queue';
$this->params['breadcrumbs'][] = ['label' => 'Mail Queues', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mail-queue-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/mail-queue/index.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
$this->title = 'Mail Queue';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ibox">
    <div class="ibox-head">
        <div class="ibox-title"><?=$this->title?></div>
        <div class="ibox-tools">
            <?=Html::a('<b>CLEAR</b>',['mail-queue/clear'],['class'=>'btn btn-danger btn-sm']);?>
        </div>
    </div>
    <div class="ibox-body">
        <div class="table-responsive">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                // 'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    'email_to:email',
                    'bcc:email',
                    'subject',
                    'html_body:html',
                    'created_at:date',
                    ['class' => 'yii\grid\ActionColumn','template'=>'{delete}'],
                ],
            ]); ?>
        </div>
    </div>
</div>

views/mail-queue/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MailQueue */

$this->title = 'Update Mail Queue: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Mail Queues', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="mail-queue-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/mail-queue/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\MailQueue */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Mail Queues', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="mail-queue-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'sender_name:ntext',
            'sender_email:ntext',
            'email_to:ntext',
            'cc:ntext',
            'bcc:ntext',
            'subject',
            'html_body:ntext',
            'text_body:ntext',
            'reply_to:ntext',
            'charset',
            'created_at',
            'attempts',
            'last_attempt_time',
            'sent_time',
            'time_to_send',
            'swift_message:ntext',
            'attachments:ntext',
            'sent',
            'email_template:email',
        ],
    ]) ?>

</div>